### ISSUE TITLE
Bug in oautho2client

### ISSUE THREAD

**Issue by wbmacleod** [insanum/gcalcli#237]
I got gcalci to work with a clean re-install (have  to delete old config files), however it seems to use a version of oauth2client that has a bug.  gcalcli prints my agenda/calendar, but after the following error message. Solutions?
WARNING:root:No module named contrib.locked_file
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/googleapiclient/discovery_cache/**init**.py", line 38, in autodetect
    from . import file_cache
  File "/usr/lib/python2.7/site-packages/googleapiclient/discovery_cache/file_cache.py", line 32, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ImportError: No module named contrib.locked_file

**Comment by hurricanehrndz** [comment]
I can confirm the same issue.

**Comment by hurricanehrndz** [comment]
Got it working for now:
```
pip install google-api-python-client==1.4.1
pip install oauth2client==1.4.12
```

**Comment by styts** [comment]
Can confirm the problem with the current release (`gcalcli==3.3.2`).

The solution from **hurricanehrndz** worked for me.

**Comment by anthony-geoghegan** [comment]
I used `pip` to install `gcalcli-3.3.2` (which also included `google_api_python_client-1.5.0` and `oauth2client-1.4.12`). I got the same `ImportError: No module named contrib.locked_file` but thanks to the solution provided by @hurricanehrndz, it now works fine.

**Comment by agherzan** [comment]
@hurricanehrndz solution worked. Cool.

**Comment by DoomHammer** [comment]
@hurricanehrndz solution works, but shouldn't those deps be frozen in `gcalcli` code?

**Comment by hurricanehrndz** [comment]
@DoomHammer,

Yes, I believe those dependencies should be hard coded or even better yet the
location of the locked_file should get updated. I will look into doing a pull
request to address the issue. I would have thought the developer would have
fixed the issue by now.
On Wed, Apr 13, 2016 at 01:27:41AM -0700, Piotr Gaczkowski wrote:
> @hurricanehrndz solution works, but shouldn't those deps be frozen in `gcalcli` code?
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/insanum/gcalcli/issues/237#issuecomment-209300937

-- 
Best Regards,
Carlos Hernandez
4096R / 7E40 E100 C53B 0F20 0A80  E02A D46C 6686 45CE FC3F
https://sks-keyservers.net/pks/lookup?op=get&search=0x45CEFC3F

**Comment by Jannes123** [comment]
@hurricanehrndz thanks for the info.

**Comment by irishmac473** [comment]
I tried @hurricanehrndz solution on OS X and it did not work for me. Still getting the same error

**Comment by tresni** [comment]
I've finally wrapped up (I think) the testing and merging of everything into the `argpase_over_gflags` branch.  I've released an alpha build of 4.0.0 which can be installed using pip (`pip install gcalcli==4.0.0a1`)

A major thing to note:  **This is not a 100% backwards compatible change**.  In moving to argparse I tried to clean up the argument handling code to only show the arguments that actually applied for each command.  So (e.g.) `quick` won't tell you it takes `--who/--when` options that it actually doesn't understand.

The following options are understood by all commands:
* auth_host_name
* noauth_local_webserver
* auth_host_port
* logging_level
* client_id
* client_secret
* configFolder
* noincluderc
* calendar
* defaultCalendar (really only useful in your .gcalclirc)
* locale
* refresh
* nocache
* conky
* nocolor
* nolineart

Check the `--help` for each command to see which options work with which commands.  For now I've set it up so that it will simply inform you if an option is not accepted but attempt to complete the command:

```
» gcalcli --calendar bhartvigsen quick --details shorturl --who me --what something "really tomorrow at 5pm"
The following options are either no longer valid globally or just plain invalid:
  --who

  --what
  something
  really tomorrow at 5pm
New event added: https://www.google.com/calendar/event?eid=ZGtsYjAxZTJpbmx0ajFlM2VzOG5vNmJsOWcgYmhhcnR2aWdzZW5Ab3BlbmRucy5jb20
```
 
This can have some unintended effects (in this case you get an event that just says "me")

Definitely looking for people to put it through the ringer.  I've identified 2 issues since I posted the release.  If you want URL details you *must* use `--details shorturl` and there is no way to set the old `--details-descr-width` (in fact, if you ask for for `--details descr` it'll crash since it tries to interpret a binary value as an integer...  Already fixed, will be in the next alpha.)
